name: sprint daily (manual)

on:
  workflow_dispatch:
    inputs:

jobs:
  generate_burndown_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Generate burndown chart
        uses: ./
        with:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DB_BACKLOG: 8c1b7c54e2024cf991e996ad90fef610
          NOTION_DB_SPRINT_SUMMARY: 59f84e58995046ada6c1ce49b1c06cb1
          NOTION_DB_DAILY_SUMMARY: 360b9a47eb614c5eb5449a09076c40bb
          NOTION_PROPERTY_SPRINT: Sprint
          NOTION_PROPERTY_ESTIMATE: Estimate
          NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE: Completed|Released
      - name: Commit burndown chart
        run: |
          git config --local user.email "galkina.s.a@gmail.com"
          git config --local user.name "sgalkina"
          git add ./out
          git commit -m "run: upload new burndown chart"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
